name: CI HW1

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Test
        # Not to use "make autograde" because it's for grading purpose and the recipe ignores errors.
        run: ARGS='bash -c "make -j project && cd tests/hw1 && python3 test.py --scanner ~/hw/src/scanner"' make activate
