name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Grade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Auto grade
        run: ARGS="make autograde" make activate
